###################################
## slå på ytterbelsyningen baserat på ljussensorn utomhus
##
## last changed: 2018-04-15
###################################
- alias: '004: Ytterbelysningen on'
  id: '004'
  trigger:
    - platform: state
      entity_id: switch.ljussensor
      to: 'on'
      for:
        minutes: 15
  condition: []
  action:
    - service: switch.turn_on
      data:
        entity_id: group.ytterbelysningen
    - service: light.turn_on
      data:
        entity_id: group.ytterbelysningen
    - service: notify.ios_danell
      data:
        message: "outdoor lights on"
        title: "lights"