###################################
## Stäng av belysning i sovrum samt allrum 
##
## last changed: 2018-05-04
###################################
- alias: '007: Overvaningen sovrum allrum off'
  id: '007'
  trigger:
    - platform: time
      at: '22:45'
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity_id: 
          - switch.sovrum
    - service: light.turn_off
      data:
        entity_id: 
          - light.allrum
