###################################
## auto stänger av lampora i barnen rum om vi är hemma 21:00
##
## last changed: 2017-11-06
###################################
- alias: '008: Overvaningen barnen off'
  id: '008'
  trigger:
    - platform: time
      at: '21:00'
  condition:
  - condition: state
    entity_id: alarm_control_panel.drivhusslingan_alarm
    state: disarmed
  action:
    - service: switch.turn_off
      data:
        entity_id: 
          - group.Lampor1
         
        
        
      