###################################
## auto Dimmra och slå av belysning för FILM
##
## last changed: 2017-11-06
###################################
- alias: '010: dimm for Movie'
  id: '010'
  trigger:
    - platform: state
      entity_id: sensor.family_room
      to: Film
  condition:
  - condition: sun
    after: sunset
  action:
    - service: switch.turn_off
      data:
        entity_id: 
          - switch.fonster_bak2
    - service: light.turn_on
      data:
        entity_id: group.Lampor7
        brightness_pct: 5 
        transition: 15                