###################################
## kontrollera taklampan i hallen och trappan baserat på rörelse och ljus
##
## last changed: 2018-05-04
###################################
- alias: '018: Dimm hallen after motion'
  id: '018'
  trigger:
    - platform: state
      entity_id: binary_sensor.hue_pir_hallen
      to: 'off'
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:30'
        before: '20:00'
      - condition: state
        entity_id: sensor.dark_hallen
        state: 'True'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_roof
        brightness_pct: 40
        transition: 10
    - service: light.turn_on
      data:
        entity_id: light.trappan
        brightness_pct: 60
        transition: 10