###################################
## auto tänd bänkbelysning vid rörelse
##
## last changed: 2018-02-25
###################################
- alias: '022: Tänd köket vid rörelse'
  id: '022'
  trigger:
    - platform: state
      entity_id: switch.rorelse_koket
      to: 'on'
  condition: []
  action:
    - service: light.turn_on
      data:
        entity_id: group.Lampor9
        brightness_pct: 99
        transition: 2