###################################
## auto controllerar ytterbelsyningen 
##
## last changed: 2017-12-08
###################################
- alias: '022: Tänd köket vid rörelse'
  id: '022'
  trigger:
    - platform: state
      entity_id: switch.rorelse_koket
      to: 'on'
  condition: []
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kok1