###################################
## meddela ny enhet upptäckt
##
## last changed: 2018-01-04
###################################
- alias: '023: Släck köket efter rörelse'
  id: '023'
  trigger:
    - platform: state
      entity_id: switch.rorelse_koket
      to: 'off'
      for:
        minutes: 1
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.kok1
        
        