###################################
## Dimmra köket efter ingen rörelse
##
## last changed: 2018-05-11
###################################
- alias: '023: Släck köket efter rörelse'
  id: '023'
  trigger:
    - platform: state
      entity_id: binary_sensor.xiaomi_pir_1
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.larmstatus
      state: 'off'
    - condition: state
      entity_id: input_boolean.nightstatus
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 40
        transition: 10