###################################
## Dimmra köket efter ingen rörelse
##
## last changed: 2018-04-25
###################################
- alias: '023: Släck köket efter rörelse'
  id: '023'
  trigger:
    - platform: state
      entity_id: switch.rorelse_koket
      to: 'off'
      for:
        minutes: 1
  condition: []
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 40
        transition: 10