###################################
## Meddela ljussensor på
##
## last changed: 2018-01-05
###################################
- alias: '025: Ljussensor på'
  id: '025'
  trigger:
    - platform: state
      entity_id: switch.ljussensor
  condition: []
  action:
    - service: notify.ios_danell
      data:
        message: "ljussensorn changed"
        title: "Ljussensor"
