###################################
## Turn off TV light when TV is off
##
## last changed: 2018-01-05
###################################
- alias: '027: Släck TV'
  id: '027'
  trigger:
    - platform: state
      entity_id: remote.hub1
      to: 'off'
  condition: []
  action:
    - service: light.turn_off
      data:
        entity_id: light.tv
        
        