###################################
## Meddela när fia byter zon
##
## last changed: 2018-04-25
###################################
- alias: '033: Fia new state'
  id: '033'
  trigger:
    platform: state
    entity_id: sensor.fia
  action:
    service: notify.ios_danell
    data_template:
      message: >
        Fia just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}