##################################################################################################
# Hallen smart buttons                                                                           #
# Version 1.0.0 last changed 2018-02-20                                                          #
# Created for and tested with Home Assistant Hassio version 0.63.3                               #
# Creator Mikael Danell SHG                                                                      #
##################################################################################################

# Automation section
automation:

#
  - alias: "Left button 1"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.hall_b1"}
    condition:
    - condition: state
      entity_id: input_boolean.hallen_left1
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallen_left1
      - service: homeassistant.turn_off
        entity_id: input_boolean.hallen_night_left1, input_boolean.hallen_night_left2
      - service: scene.turn_on
        entity_id: scene.light1

  - alias: "Left button 2"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.hall_b1"}
    condition:
    - condition: state
      entity_id: input_boolean.hallen_left1
      state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallen_left2
      - service: scene.turn_on
        entity_id: scene.light2

  - alias: "Left button 3"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.hall_b1"}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.hallen_left2
          state: 'on'
        - condition: state
          entity_id: input_boolean.hallen_left3
          state: 'off'
    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.hallen_left3
      
  - alias: "Left button night 1"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "off", "entity_id": "switch.hall_b1"}
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallen_night_left1
      - service: homeassistant.turn_off
        entity_id: input_boolean.hallen_left1, input_boolean.hallen_left2, input_boolean.hallen_left3
      - service: scene.turn_on
        entity_id: scene.light1_off

  - alias: "Left button night 2"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "off", "entity_id": "switch.hall_b1"}
    condition:
    - condition: state
      entity_id: input_boolean.hallen_night_left1
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.hallen_night_left2

      
  - alias: "Right button 1"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.hall_b2"}
    condition:
    - condition: state
      entity_id: input_boolean.hallen_right1
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallen_right1
      - service: scene.turn_on
        entity_id: scene.Daymode1

  - alias: "Right button 2"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.hall_b2"}
    condition:
    - condition: state
      entity_id: input_boolean.hallen_right1
      state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallen_right2
      - service: scene.turn_on
        entity_id: scene.Daymode2

  - alias: "Right button 3"
    initial_state: true
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.hall_b2"}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.hallen_right2
          state: 'on'
        - condition: state
          entity_id: input_boolean.hallen_right3
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallen_right3
      - service: scene.turn_on
        entity_id: scene.Daymode3

# Bolean section
input_boolean:
  hallen_left1:
    name: Day Mode 1
    initial: off
    icon: mdi:numeric-1-box-outline
  hallen_left2:
    name: Day Mode 2
    initial: off
    icon: mdi:numeric-2-box-outline
  hallen_left3:
    name: Day Mode 3
    initial: off
    icon: mdi:numeric-3-box-outline
  hallen_right1:
    name: Day Mode 1
    icon: mdi:numeric-1-box-outline
  hallen_right2:
    name: Day Mode 2
    icon: mdi:numeric-2-box-outline
  hallen_right3:
    name: Day Mode 3
    icon: mdi:numeric-3-box-outline
  hallen_right4:
    name: Day Mode 4
    icon: mdi:numeric-4-box-outline
  hallen_right5:
    name: Day Mode 5
    icon: mdi:numeric-5-box-outline
  hallen_night_left1:
    name: Night Mode 1
    initial: off
    icon: mdi:numeric-1-box
  hallen_night_left2:
    name: Night Mode 2
    initial: off
    icon: mdi:numeric-2-box


# Group section
group:

  button_view:
    view: yes
    name: button
    icon: mdi:remote
    entities:
      - group.button_controls_left
      - group.button_controls_right


  button_controls_left:
    control: hidden
    name: "knappläge vänster"
    entities:
      - switch.hall_b1
      - automation.left_button
      - input_boolean.hallen_left1
      - input_boolean.hallen_left2
      - input_boolean.hallen_left3
      - input_boolean.hallen_night_left1
      - input_boolean.hallen_night_left2


  button_controls_right:
    control: hidden
    name: "knappläge höger"
    entities:
      - switch.hall_b2
      - automation.right_button
      - input_boolean.hallen_right1
      - input_boolean.hallen_right2
      - input_boolean.hallen_right3

# Script section
script:
# 
  button_left_on:
    sequence:
    - service: switch.turn_on
      entity_id: switch.motorvarmaren
    - service: automation.turn_on
      entity_id: automation.heater_off
      
  button_right_on:
    sequence:
    - service: switch.turn_on
      entity_id: switch.motorvarmaren
    - service: automation.turn_on
      entity_id: automation.heater_off

  hall_goodmorning:
    alias: "God Morgon" 
    sequence:
      - service: media_player.sonos_snapshot
        data:
          entity_id: media_player.home
      - service: media_player.volume_set
        data:
          entity_id: media_player.home
          volume_level: 0.25
      - service: tts.google_say
        entity_id: media_player.home
        data_template:
          message: >-
             God morgon. Det är just nu {{states.sensor.netatmo_ute_temperature.state|round}} grader utomhus och det blåser {{states.sensor.vind_nu.state}}m/s.
      - delay: '00:00:06'
      - service: media_player.sonos_restore
        data:
          entity_id: media_player.home

  hall_goodday:
    alias: "God dag" 
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: media_player.home
      - service: tts.google_say
        entity_id: media_player.home
        data_template:
          message: >-
             God dag. Det är just nu {{states.sensor.netatmo_ute_temperature.state|round}} grader utomhus och det blåser {{states.sensor.vind_nu.state}}m/s.
      - delay: '00:00:06'
      - service: media_player.sonos_restore
        data_template:
          entity_id: media_player.home

  hall_goodevning:
    alias: "God kväll" 
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: media_player.home
      - service: tts.google_say
        entity_id: media_player.home
        data_template:
          message: >-
             God kväll.
      - delay: '00:00:03'
      - service: media_player.sonos_restore
        data_template:
          entity_id: media_player.home

  hall_goodnight:
    alias: "God natt" 
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: media_player.home
      - service: tts.google_say
        entity_id: media_player.home
        data_template:
          message: >-
             God natt.
      - delay: '00:00:03'
      - service: media_player.sonos_restore
        data_template:
          entity_id: media_player.home
